$(function () {
    $('#messageContent').summernote()
    $('#announcementContent').summernote()
    $('#commentContent').summernote()
    $('#system_title_header').summernote()
    $('#system_description').summernote()
    $('#system_logo').summernote()
    $('#IT_REMARKS').summernote()
    $('#IT_PURPOSE').summernote()
  })